"""Initial schema

Revision ID: 5b4c0bcaf37f
Revises: 
Create Date: 2026-02-03 02:12:16.673475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b4c0bcaf37f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('book_id', sa.String(length=100), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('illustrator', sa.Text(), nullable=True),
    sa.Column('release_date', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('original_publication', sa.Text(), nullable=True),
    sa.Column('credits', sa.Text(), nullable=True),
    sa.Column('copyright_status', sa.String(length=100), nullable=True),
    sa.Column('downloads', sa.String(length=50), nullable=True),
    sa.Column('cover_url', sa.Text(), nullable=True),
    sa.Column('files', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('ratings_average', sa.Float(), nullable=True),
    sa.Column('ratings_count', sa.BigInteger(), nullable=True),
    sa.Column('want_to_read_count', sa.BigInteger(), nullable=True),
    sa.Column('edition_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_books_source_book_id', 'books', ['source', 'book_id'], unique=True)
    op.create_index(op.f('ix_books_book_id'), 'books', ['book_id'], unique=False)
    op.create_index(op.f('ix_books_source'), 'books', ['source'], unique=False)
    op.create_table('seed_offsets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('last_offset', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seed_offsets')
    op.drop_index(op.f('ix_books_source'), table_name='books')
    op.drop_index(op.f('ix_books_book_id'), table_name='books')
    op.drop_index('idx_books_source_book_id', table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
