"""Fix SeedOffset columns

Revision ID: b4137bddfb3a
Revises: 5b4c0bcaf37f
Create Date: 2026-02-03 02:22:40.626264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4137bddfb3a'
down_revision: Union[str, Sequence[str], None] = '5b4c0bcaf37f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('books_author_idx'), table_name='books')
    op.drop_index(op.f('books_source_book_id_idx'), table_name='books')
    op.drop_index(op.f('books_title_idx'), table_name='books')
    op.add_column('seed_offsets', sa.Column('position', sa.BigInteger(), nullable=False))
    op.add_column('seed_offsets', sa.Column('last_book_id', sa.String(length=100), nullable=True))
    op.drop_column('seed_offsets', 'last_offset')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seed_offsets', sa.Column('last_offset', sa.BIGINT(), nullable=False))
    op.drop_column('seed_offsets', 'last_book_id')
    op.drop_column('seed_offsets', 'position')
    op.create_index(op.f('books_title_idx'), 'books', ['title'], unique=False)
    op.create_index(op.f('books_source_book_id_idx'), 'books', ['source', 'book_id'], unique=1)
    op.create_index(op.f('books_author_idx'), 'books', ['author'], unique=False)
    # ### end Alembic commands ###
